name: DX Scanner
on: push
jobs:
  dx-scanner:
    runs-on: ubuntu-latest
    container: dxheroes/dx-scanner:latest
    steps:
      - uses: actions/checkout@v1
      - name: Runs DX Scanner on the code
      - run: cd
      - run: ls
