name: DX Scanner
on: push
jobs:
  dx-scanne:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Runs DX Scanner on the code
        uses: Dxheroes/dx-scanner@master
        with:
          github_token: ${{ secrets.TEST }}
      - run: dx-scanner run --ci
