name: DX Scanner
on: push
jobs:
  dx-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd
      - run: ls
      - name: Runs DX Scanner on the code
        uses: docker://dxheroes/dx-scanner:latest
        with:
          github_token: ${{ secrets.TEST }}
      - run: cd
      - run: ls
      - run: dx-scanner run --ci
