name: DX Scanner
on: push
jobs:
  dx-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Runs DX Scanner on the code
        uses: docker://dxheroes/dx-scanner:latest
        with:
          github_token: "f05f7ed3818c6c6d31bfaae638f7fad2906acc31"
